sqs:
  queue_url: 'https://sqs.${self:provider.region}.amazonaws.com/${self:custom.accountId.${self:provider.stage}}/${self:provider.stage}-cfn-drift-police-queue'

ssm:
  slack_token_store: '/${self:provider.stage}/cfn/drift/police'

slack:
  channel_name: '#notice_cfn_drift_st'